[versions]
agp = "8.13.1"
kotlin = "2.2.21"

coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.0"
constraintlayout = "2.2.1"

# Lifecycle
lifecycle = "2.10.0"

# GMS (NextGen)
adsMobileSdk = "0.22.0-beta02"
playServicesAdsApi = "24.8.0"

# koin
koin = "4.1.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

# GMS (NextGen)
ads-mobile-sdk = { module = "com.google.android.libraries.ads.mobile.sdk:ads-mobile-sdk", version.ref = "adsMobileSdk" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads-api", version.ref = "playServicesAdsApi" }

# Koin
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }